# Generated by Django 3.2.5 on 2021-07-08 06:47

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=api.models.generate_unique_code, max_length=6, unique=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(default='SpaceWars', max_length=50)),
            ],
        ),
    ]
