# Generated by Django 3.2.5 on 2021-07-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_game_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='created_by',
            field=models.TextField(default='Admin'),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.TextField(default='SpaceWars'),
        ),
    ]
